# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
# Note: this is used to deploy the production Jelli Fit API to Fly.io

app = "jellifit-api"
primary_region = "lax"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
