name: Deploy API

on:
  push:
    branches:
      - main
    paths:
      - api/**
      - .github/workflows/deploy_api.yml

jobs:
  build-and-push:
    name: Deploy to Fly.io
    runs-on: ubuntu-latest
    if: github.repository == 'dirtbirb/jelli.fit'

    defaults:
      run:
        working-directory: api

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
